# Generated by Django 4.0.4 on 2022-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SmallIntegerField(max_length=32, unique=True),
        ),
    ]
